"""Initial baseline

Revision ID: 032a4b6f25ae
Revises:
Create Date: 2026-04-07 12:27:05.117990

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '032a4b6f25ae'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


