"""Add poc and onboarding fields to society

Revision ID: 3cc31f660103
Revises: 916c6509c5bd
Create Date: 2026-04-23 23:21:36.908876

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3cc31f660103'
down_revision: str | None = '916c6509c5bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('poc_name', sa.String(length=255), nullable=True))
    op.add_column('societies', sa.Column('poc_phone', sa.String(length=50), nullable=True))
    op.add_column('societies', sa.Column('poc_email', sa.String(length=255), nullable=True))
    op.add_column('societies', sa.Column('onboarded_date', sa.DateTime(), nullable=True))
    op.add_column('societies', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('societies', 'notes')
    op.drop_column('societies', 'onboarded_date')
    op.drop_column('societies', 'poc_email')
    op.drop_column('societies', 'poc_phone')
    op.drop_column('societies', 'poc_name')
    # ### end Alembic commands ###


