"""restore_identity_fields_to_society

Revision ID: 5586ce5e7607
Revises: 821429fd75aa
Create Date: 2026-05-02 19:35:48.467424

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5586ce5e7607"
down_revision: str | None = "821429fd75aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("societies", sa.Column("num_commercial", sa.Integer(), nullable=True))
    op.add_column("societies", sa.Column("cts_no", sa.String(length=100), nullable=True))
    op.add_column("societies", sa.Column("fp_no", sa.String(length=100), nullable=True))
    op.add_column("societies", sa.Column("tps_name", sa.String(length=255), nullable=True))
    op.add_column("societies", sa.Column("ward", sa.String(length=20), nullable=True))
    op.add_column("societies", sa.Column("village", sa.String(length=255), nullable=True))
    op.add_column("societies", sa.Column("taluka", sa.String(length=255), nullable=True))
    op.add_column("societies", sa.Column("district", sa.String(length=255), nullable=True))
    op.add_column("societies", sa.Column("plot_area_sqm", sa.Float(), nullable=True))
    op.add_column("societies", sa.Column("road_width_m", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("societies", "road_width_m")
    op.drop_column("societies", "plot_area_sqm")
    op.drop_column("societies", "district")
    op.drop_column("societies", "taluka")
    op.drop_column("societies", "village")
    op.drop_column("societies", "ward")
    op.drop_column("societies", "tps_name")
    op.drop_column("societies", "fp_no")
    op.drop_column("societies", "cts_no")
    op.drop_column("societies", "num_commercial")
    # ### end Alembic commands ###
