"""consolidated_baseline_with_structural_changes

Revision ID: 821429fd75aa
Revises:
Create Date: 2026-05-02 19:09:47.942765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "821429fd75aa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_actor_action", "audit_logs", ["actor_id", "action"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "get_started_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("society_name", sa.String(length=500), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_get_started_requests_email"), "get_started_requests", ["email"], unique=False
    )
    op.create_table(
        "landing_page_content",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("section", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column("cta_text", sa.String(length=100), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_landing_page_content_section"), "landing_page_content", ["section"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clerk_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "PMC",
                "SOCIETY",
                "BUILDER",
                "LAWYER",
                "VIEWER",
                name="user_role",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("experience", sa.String(length=100), nullable=True),
        sa.Column("projects_completed", sa.String(length=100), nullable=True),
        sa.Column("specialization", sa.String(length=255), nullable=True),
        sa.Column("portfolio_description", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("portfolio_url", sa.String(length=500), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_org", "users", ["organization"], unique=False)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "enquiries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "IN_PROGRESS",
                "RESOLVED",
                "CLOSED",
                name="enquiry_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enquiries_email"), "enquiries", ["email"], unique=False)
    op.create_index("ix_enquiries_status", "enquiries", ["status"], unique=False)
    op.create_table(
        "societies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("poc_name", sa.String(length=255), nullable=True),
        sa.Column("poc_phone", sa.String(length=50), nullable=True),
        sa.Column("poc_email", sa.String(length=255), nullable=True),
        sa.Column("onboarded_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("num_flats", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ACTIVE",
                "ONBOARDED",
                "INVITATION_SENT",
                "REPORT_PENDING",
                "TENDER_PENDING",
                "TENDER_PUBLISHED",
                "TENDER_REVIEW_PENDING",
                "BUILDER_FINALIZED",
                "MANUAL_PROCESS",
                name="society_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_societies_created_by", "societies", ["created_by"], unique=False)
    op.create_index(op.f("ix_societies_name"), "societies", ["name"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("invite_token", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "DECLINED",
                "EXPIRED",
                name="invite_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "organization", name="uq_team_email_org"),
        sa.UniqueConstraint("invite_token"),
    )
    op.create_index(
        op.f("ix_team_members_organization"), "team_members", ["organization"], unique=False
    )
    op.create_table(
        "feasibility_reports",
        sa.Column("society_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("report_path", sa.String(length=500), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "IN_PROGRESS",
                "PROCESSING",
                "COMPLETED",
                "FINAL",
                "FAILED",
                name="report_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_buffer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_log", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_analysis", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("ward", sa.String(length=20), nullable=True),
        sa.Column("village", sa.String(length=255), nullable=True),
        sa.Column("cts_no", sa.String(length=100), nullable=True),
        sa.Column("fp_no", sa.String(length=100), nullable=True),
        sa.Column("fsi", sa.Float(), nullable=True),
        sa.Column("plot_area", sa.Float(), nullable=True),
        sa.Column("estimated_value", sa.String(length=100), nullable=True),
        sa.Column("existing_units", sa.Integer(), nullable=True),
        sa.Column("proposed_units", sa.Integer(), nullable=True),
        sa.Column("feasibility", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["society_id"], ["societies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feasibility_created_at", "feasibility_reports", ["created_at"], unique=False
    )
    op.create_index("ix_feasibility_society", "feasibility_reports", ["society_id"], unique=False)
    op.create_index("ix_feasibility_user", "feasibility_reports", ["user_id"], unique=False)
    op.create_table(
        "society_reports",
        sa.Column("society_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("report_type", sa.String(length=100), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "IN_PROGRESS",
                "PROCESSING",
                "COMPLETED",
                "FINAL",
                "FAILED",
                name="report_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["society_id"], ["societies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "society_tenders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("society_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("budget_min", sa.Float(), nullable=True),
        sa.Column("budget_max", sa.Float(), nullable=True),
        sa.Column("estimated_value", sa.String(length=50), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "OPEN", "CLOSED", "AWARDED", name="tender_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("awarded_to", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["awarded_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["society_id"], ["societies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("society_tenders")
    op.drop_table("society_reports")
    op.drop_index("ix_feasibility_user", table_name="feasibility_reports")
    op.drop_index("ix_feasibility_society", table_name="feasibility_reports")
    op.drop_index("ix_feasibility_created_at", table_name="feasibility_reports")
    op.drop_table("feasibility_reports")
    op.drop_index(op.f("ix_team_members_organization"), table_name="team_members")
    op.drop_table("team_members")
    op.drop_index(op.f("ix_societies_name"), table_name="societies")
    op.drop_index("ix_societies_created_by", table_name="societies")
    op.drop_table("societies")
    op.drop_index("ix_enquiries_status", table_name="enquiries")
    op.drop_index(op.f("ix_enquiries_email"), table_name="enquiries")
    op.drop_table("enquiries")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index("ix_users_org", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_index(op.f("ix_landing_page_content_section"), table_name="landing_page_content")
    op.drop_table("landing_page_content")
    op.drop_index(op.f("ix_get_started_requests_email"), table_name="get_started_requests")
    op.drop_table("get_started_requests")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_action", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
