"""add_ocr_fields_to_societies

Revision ID: 916c6509c5bd
Revises: add_fp_tps_cts
Create Date: 2026-04-23 00:28:14.534360

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '916c6509c5bd'
down_revision: str | None = 'add_fp_tps_cts'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('society_age', sa.Integer(), nullable=True))
    op.add_column('societies', sa.Column('existing_bua_sqft', sa.Float(), nullable=True))
    op.add_column('societies', sa.Column('pfa_sqft', sa.Float(), nullable=True))
    op.add_column('societies', sa.Column('ocr_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('societies', 'ocr_data')
    op.drop_column('societies', 'pfa_sqft')
    op.drop_column('societies', 'existing_bua_sqft')
    op.drop_column('societies', 'society_age')
    # ### end Alembic commands ###


