"""strip_society_model_to_bare_essentials

Revision ID: fd819f308a81
Revises: 5586ce5e7607
Create Date: 2026-05-02 20:07:05.793452

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd819f308a81"
down_revision: str | None = "5586ce5e7607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("societies", "plot_area_sqm")
    op.drop_column("societies", "ward")
    op.drop_column("societies", "road_width_m")
    op.drop_column("societies", "taluka")
    op.drop_column("societies", "district")
    op.drop_column("societies", "fp_no")
    op.drop_column("societies", "num_commercial")
    op.drop_column("societies", "tps_name")
    op.drop_column("societies", "village")
    op.drop_column("societies", "cts_no")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "societies", sa.Column("cts_no", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.add_column(
        "societies",
        sa.Column("village", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "societies",
        sa.Column("tps_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "societies", sa.Column("num_commercial", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "societies", sa.Column("fp_no", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.add_column(
        "societies",
        sa.Column("district", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "societies", sa.Column("taluka", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "societies",
        sa.Column(
            "road_width_m", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "societies", sa.Column("ward", sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    op.add_column(
        "societies",
        sa.Column(
            "plot_area_sqm", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
